"""Bake the giant forename/surname CSVs into a compact Python module.

The raw CSVs are too large to ship as runtime data (12M + 21M lines). This
script reads them once and emits `core/content/_names_data.py` containing the
top-N names per (country, gender) keyed by ISO-2 country code.

Accepts either the plain `.csv` or the gzipped `.csv.gz` form — the gzipped
files are what ships in the repo (LFS), the plain ones are gitignored.

Run from the project root:

    python scripts/build_name_data.py
"""
from __future__ import annotations

import csv
import gzip
import sys
from collections import defaultdict
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, TextIO

HERE = Path(__file__).resolve().parent.parent
DATA_DIR = HERE / "data"
FORENAMES_CSV = DATA_DIR / "forenames.csv"
SURNAMES_CSV = DATA_DIR / "surnames.csv"
OUT_PATH = HERE / "core" / "content" / "_names_data.py"

TOP_PER_GROUP = 40  # top-N per (country, gender) for forenames; per country for surnames


def _resolve(path: Path) -> Path | None:
    """Find either the plain or gzipped form of the requested CSV."""
    if path.exists():
        return path
    gz = path.with_suffix(path.suffix + ".gz")
    if gz.exists():
        return gz
    return None


@contextmanager
def _open_csv(path: Path) -> Iterator[TextIO]:
    """Open .csv or .csv.gz transparently as a text stream."""
    if path.suffix == ".gz":
        with gzip.open(path, "rt", encoding="utf-8", newline="") as f:
            yield f
    else:
        with path.open(encoding="utf-8", newline="") as f:
            yield f


def top_forenames() -> dict[str, dict[str, list[str]]]:
    buckets: dict[tuple[str, str], list[tuple[int, str]]] = defaultdict(list)
    resolved = _resolve(FORENAMES_CSV)
    if resolved is None:
        raise FileNotFoundError(f"missing {FORENAMES_CSV} (and .gz)")
    with _open_csv(resolved) as f:
        reader = csv.reader(f)
        next(reader, None)  # header
        for row in reader:
            if len(row) < 4:
                continue
            forename, gender, country, count = row[0], row[1], row[2], row[3]
            try:
                c = int(count)
            except ValueError:
                continue
            buckets[(country, gender)].append((c, forename))

    out: dict[str, dict[str, list[str]]] = {}
    for (country, gender), items in buckets.items():
        items.sort(reverse=True)
        names = [n for _, n in items[:TOP_PER_GROUP]]
        out.setdefault(country, {})[gender] = names
    return out


def top_surnames() -> dict[str, list[str]]:
    # Surnames are gendered in the CSV but we collapse — same surname pool for
    # M and F per country.
    buckets: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    resolved = _resolve(SURNAMES_CSV)
    if resolved is None:
        raise FileNotFoundError(f"missing {SURNAMES_CSV} (and .gz)")
    with _open_csv(resolved) as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            if len(row) < 4:
                continue
            surname, _gender, country, count = row[0], row[1], row[2], row[3]
            try:
                c = int(count)
            except ValueError:
                continue
            buckets[country][surname] += c

    out: dict[str, list[str]] = {}
    for country, name_counts in buckets.items():
        items = sorted(name_counts.items(), key=lambda kv: kv[1], reverse=True)
        out[country] = [n for n, _ in items[:TOP_PER_GROUP]]
    return out


def emit(forenames: dict[str, dict[str, list[str]]], surnames: dict[str, list[str]]) -> None:
    countries = sorted(set(forenames) | set(surnames))
    lines: list[str] = []
    lines.append('"""Auto-generated by scripts/build_name_data.py — DO NOT EDIT BY HAND."""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("FORENAMES: dict[str, dict[str, list[str]]] = {")
    for cc in countries:
        gmap = forenames.get(cc, {})
        if not gmap:
            continue
        lines.append(f"    {cc!r}: {{")
        for g in ("M", "F"):
            names = gmap.get(g, [])
            if not names:
                continue
            lines.append(f"        {g!r}: {names!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("SURNAMES: dict[str, list[str]] = {")
    for cc in countries:
        names = surnames.get(cc, [])
        if not names:
            continue
        lines.append(f"    {cc!r}: {names!r},")
    lines.append("}")
    lines.append("")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if _resolve(FORENAMES_CSV) is None:
        print(f"missing {FORENAMES_CSV} (or {FORENAMES_CSV}.gz)", file=sys.stderr)
        return 1
    if _resolve(SURNAMES_CSV) is None:
        print(f"missing {SURNAMES_CSV} (or {SURNAMES_CSV}.gz)", file=sys.stderr)
        return 1
    print("reading forenames…")
    fn = top_forenames()
    print(f"  {len(fn)} countries")
    print("reading surnames…")
    sn = top_surnames()
    print(f"  {len(sn)} countries")
    emit(fn, sn)
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
