"""Bake the giant forename/surname CSVs into a compact Python module.

The raw CSVs are too large to ship as runtime data (12M + 21M lines). This
script reads them once and emits `core/content/_names_data.py` containing the
top-N names per (country, gender) keyed by ISO-2 country code.

Run from the project root:

    python scripts/build_name_data.py
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
FORENAMES_CSV = HERE / "forenames.csv"
SURNAMES_CSV = HERE / "surnames.csv"
OUT_PATH = HERE / "core" / "content" / "_names_data.py"

TOP_PER_GROUP = 40  # top-N per (country, gender) for forenames; per country for surnames


def top_forenames() -> dict[str, dict[str, list[str]]]:
    buckets: dict[tuple[str, str], list[tuple[int, str]]] = defaultdict(list)
    with FORENAMES_CSV.open(encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader, None)  # header
        for row in reader:
            if len(row) < 4:
                continue
            forename, gender, country, count = row[0], row[1], row[2], row[3]
            try:
                c = int(count)
            except ValueError:
                continue
            buckets[(country, gender)].append((c, forename))

    out: dict[str, dict[str, list[str]]] = {}
    for (country, gender), items in buckets.items():
        items.sort(reverse=True)
        names = [n for _, n in items[:TOP_PER_GROUP]]
        out.setdefault(country, {})[gender] = names
    return out


def top_surnames() -> dict[str, list[str]]:
    # Surnames are gendered in the CSV but we collapse — same surname pool for
    # M and F per country.
    buckets: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    with SURNAMES_CSV.open(encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader, None)
        for row in reader:
            if len(row) < 4:
                continue
            surname, _gender, country, count = row[0], row[1], row[2], row[3]
            try:
                c = int(count)
            except ValueError:
                continue
            buckets[country][surname] += c

    out: dict[str, list[str]] = {}
    for country, name_counts in buckets.items():
        items = sorted(name_counts.items(), key=lambda kv: kv[1], reverse=True)
        out[country] = [n for n, _ in items[:TOP_PER_GROUP]]
    return out


def emit(forenames: dict[str, dict[str, list[str]]], surnames: dict[str, list[str]]) -> None:
    countries = sorted(set(forenames) | set(surnames))
    lines: list[str] = []
    lines.append('"""Auto-generated by scripts/build_name_data.py — DO NOT EDIT BY HAND."""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("FORENAMES: dict[str, dict[str, list[str]]] = {")
    for cc in countries:
        gmap = forenames.get(cc, {})
        if not gmap:
            continue
        lines.append(f"    {cc!r}: {{")
        for g in ("M", "F"):
            names = gmap.get(g, [])
            if not names:
                continue
            lines.append(f"        {g!r}: {names!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("SURNAMES: dict[str, list[str]] = {")
    for cc in countries:
        names = surnames.get(cc, [])
        if not names:
            continue
        lines.append(f"    {cc!r}: {names!r},")
    lines.append("}")
    lines.append("")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not FORENAMES_CSV.exists():
        print(f"missing {FORENAMES_CSV}", file=sys.stderr)
        return 1
    if not SURNAMES_CSV.exists():
        print(f"missing {SURNAMES_CSV}", file=sys.stderr)
        return 1
    print("reading forenames…")
    fn = top_forenames()
    print(f"  {len(fn)} countries")
    print("reading surnames…")
    sn = top_surnames()
    print(f"  {len(sn)} countries")
    emit(fn, sn)
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
