"""Generate ui/mock_snapshot.js from the canonical Python core.

The browser-only preview (opening ui/index.html without Qt) must NOT contain a
second simulation. This script runs the real GameController, plays a short
deterministic life, and writes the resulting canonical snapshots to a JS data
file the MockBridge serves verbatim. The laws stay in Python; the JS holds only
recorded output.

    python -m scripts.gen_mock_snapshot
"""
from __future__ import annotations

import json
from pathlib import Path

from controller.game_controller import GameController
from core import economy, sim
from core.content.jobs import JOBS, education_meets
from core.rng import Rng


def _best_job(state):
    elig = [
        j for j in JOBS
        if j.track != "criminal"
        and state.character.age >= j.min_age
        and state.stats.smarts >= j.min_smarts
        and education_meets(state.education.level, j.min_education)
        and not (j.required_field and (not state.education.degree_completed
                                       or state.education.degree_field != j.required_field))
    ]
    return max(elig, key=lambda j: j.salary) if elig else None


def main() -> None:
    c = GameController()
    creation = c.snapshot()  # CREATION-mode snapshot (countries etc.)

    c.new_game(seed=20260522, name="", gender="Female", country="UK", talent="Academics")
    choice_rng = Rng(c.state.seed ^ 0x5EED)
    # Play to a settled mid-30s state so the preview shows a populated UI.
    while c.state.character.age < 34:
        if c.state.pending_event_id is not None:
            ev = sim.get_pending_event(c.state)
            n = len(ev["choices"]) if ev else 1
            c.choose(choice_rng.randint(0, max(0, n - 1)))
            continue
        if c.state.career is None and c.state.character.age >= 18:
            job = _best_job(c.state)
            if job is not None:
                economy.apply_for_job(c.state, job.job_id)
        c.age_up()
    # Clear any transient popups so the preview opens on the main hub.
    for attr in ("pending_job_offer", "pending_promotion", "pending_job_loss",
                 "pending_career_setback", "job_application_error"):
        setattr(c.state, attr, None)
    playing = c.snapshot()

    out = Path(__file__).resolve().parents[1] / "ui" / "mock_snapshot.js"
    body = (
        "// GENERATED by scripts/gen_mock_snapshot.py — do not edit by hand.\n"
        "// Canonical snapshots recorded from the Python core. The browser\n"
        "// preview serves these verbatim; it runs NO simulation of its own.\n"
        f"window.MOCK_SNAPSHOT_CREATION = {json.dumps(creation, default=str)};\n"
        f"window.MOCK_SNAPSHOT_PLAYING = {json.dumps(playing, default=str)};\n"
    )
    out.write_text(body, encoding="utf-8")
    print(f"Wrote {out} ({len(body):,} bytes); playing age={playing['character']['age']}")


if __name__ == "__main__":
    main()
