const FLAG_ASSET_MAP = {
  "AF": { name: "Afghanistan", continent: "asia", path: "flags-svg/asia/AF.svg" },
  "AL": { name: "Albania", continent: "europe", path: "flags-svg/europe/AL.svg" },
  "DZ": { name: "Algeria", continent: "africa", path: "flags-svg/africa/DZ.svg" },
  "AO": { name: "Angola", continent: "africa", path: "flags-svg/africa/AO.svg" },
  "AR": { name: "Argentina", continent: "south-america", path: "flags-svg/south-america/AR.svg" },
  "AT": { name: "Austria", continent: "europe", path: "flags-svg/europe/AT.svg" },
  "AZ": { name: "Azerbaijan", continent: "asia", path: "flags-svg/asia/AZ.svg" },
  "BH": { name: "Bahrain", continent: "asia", path: "flags-svg/asia/BH.svg" },
  "BD": { name: "Bangladesh", continent: "asia", path: "flags-svg/asia/BD.svg" },
  "BE": { name: "Belgium", continent: "europe", path: "flags-svg/europe/BE.svg" },
  "BO": { name: "Bolivia", continent: "south-america", path: "flags-svg/south-america/BO.svg" },
  "BW": { name: "Botswana", continent: "africa", path: "flags-svg/africa/BW.svg" },
  "BR": { name: "Brazil", continent: "south-america", path: "flags-svg/south-america/BR.svg" },
  "BN": { name: "Brunei", continent: "asia", path: "flags-svg/asia/BN.svg" },
  "BG": { name: "Bulgaria", continent: "europe", path: "flags-svg/europe/BG.svg" },
  "BF": { name: "Burkina Faso", continent: "africa", path: "flags-svg/africa/BF.svg" },
  "BI": { name: "Burundi", continent: "africa", path: "flags-svg/africa/BI.svg" },
  "KH": { name: "Cambodia", continent: "asia", path: "flags-svg/asia/KH.svg" },
  "CM": { name: "Cameroon", continent: "africa", path: "flags-svg/africa/CM.svg" },
  "CA": { name: "Canada", continent: "north-america", path: "flags-svg/north-america/CA.svg" },
  "CL": { name: "Chile", continent: "south-america", path: "flags-svg/south-america/CL.svg" },
  "CN": { name: "China", continent: "asia", path: "flags-svg/asia/CN.svg" },
  "CO": { name: "Colombia", continent: "south-america", path: "flags-svg/south-america/CO.svg" },
  "CR": { name: "Costa Rica", continent: "north-america", path: "flags-svg/north-america/CR.svg" },
  "HR": { name: "Croatia", continent: "europe", path: "flags-svg/europe/HR.svg" },
  "CY": { name: "Cyprus", continent: "asia", path: "flags-svg/asia/CY.svg" },
  "CZ": { name: "Czechia", continent: "europe", path: "flags-svg/europe/CZ.svg" },
  "DK": { name: "Denmark", continent: "europe", path: "flags-svg/europe/DK.svg" },
  "DJ": { name: "Djibouti", continent: "africa", path: "flags-svg/africa/DJ.svg" },
  "EC": { name: "Ecuador", continent: "south-america", path: "flags-svg/south-america/EC.svg" },
  "EG": { name: "Egypt", continent: "africa", path: "flags-svg/africa/EG.svg" },
  "SV": { name: "El Salvador", continent: "north-america", path: "flags-svg/north-america/SV.svg" },
  "EE": { name: "Estonia", continent: "europe", path: "flags-svg/europe/EE.svg" },
  "ET": { name: "Ethiopia", continent: "africa", path: "flags-svg/africa/ET.svg" },
  "FJ": { name: "Fiji", continent: "oceania", path: "flags-svg/oceania/FJ.svg" },
  "FI": { name: "Finland", continent: "europe", path: "flags-svg/europe/FI.svg" },
  "FR": { name: "France", continent: "europe", path: "flags-svg/europe/FR.svg" },
  "GE": { name: "Georgia", continent: "asia", path: "flags-svg/asia/GE.svg" },
  "DE": { name: "Germany", continent: "europe", path: "flags-svg/europe/DE.svg" },
  "GH": { name: "Ghana", continent: "africa", path: "flags-svg/africa/GH.svg" },
  "GR": { name: "Greece", continent: "europe", path: "flags-svg/europe/GR.svg" },
  "GT": { name: "Guatemala", continent: "north-america", path: "flags-svg/north-america/GT.svg" },
  "HT": { name: "Haiti", continent: "north-america", path: "flags-svg/north-america/HT.svg" },
  "HN": { name: "Honduras", continent: "north-america", path: "flags-svg/north-america/HN.svg" },
  "HK": { name: "Hong Kong", continent: "asia", path: "flags-svg/asia/HK.svg" },
  "HU": { name: "Hungary", continent: "europe", path: "flags-svg/europe/HU.svg" },
  "IS": { name: "Iceland", continent: "europe", path: "flags-svg/europe/IS.svg" },
  "IN": { name: "India", continent: "asia", path: "flags-svg/asia/IN.svg" },
  "ID": { name: "Indonesia", continent: "asia", path: "flags-svg/asia/ID.svg" },
  "IR": { name: "Iran", continent: "asia", path: "flags-svg/asia/IR.svg" },
  "IQ": { name: "Iraq", continent: "asia", path: "flags-svg/asia/IQ.svg" },
  "IE": { name: "Ireland", continent: "europe", path: "flags-svg/europe/IE.svg" },
  "IL": { name: "Israel", continent: "asia", path: "flags-svg/asia/IL.svg" },
  "IT": { name: "Italy", continent: "europe", path: "flags-svg/europe/IT.svg" },
  "JM": { name: "Jamaica", continent: "north-america", path: "flags-svg/north-america/JM.svg" },
  "JP": { name: "Japan", continent: "asia", path: "flags-svg/asia/JP.svg" },
  "JO": { name: "Jordan", continent: "asia", path: "flags-svg/asia/JO.svg" },
  "KZ": { name: "Kazakhstan", continent: "asia", path: "flags-svg/asia/KZ.svg" },
  "KW": { name: "Kuwait", continent: "asia", path: "flags-svg/asia/KW.svg" },
  "LB": { name: "Lebanon", continent: "asia", path: "flags-svg/asia/LB.svg" },
  "LY": { name: "Libya", continent: "africa", path: "flags-svg/africa/LY.svg" },
  "LT": { name: "Lithuania", continent: "europe", path: "flags-svg/europe/LT.svg" },
  "LU": { name: "Luxembourg", continent: "europe", path: "flags-svg/europe/LU.svg" },
  "MO": { name: "Macao", continent: "asia", path: "flags-svg/asia/MO.svg" },
  "MY": { name: "Malaysia", continent: "asia", path: "flags-svg/asia/MY.svg" },
  "MV": { name: "Maldives", continent: "asia", path: "flags-svg/asia/MV.svg" },
  "MT": { name: "Malta", continent: "europe", path: "flags-svg/europe/MT.svg" },
  "MU": { name: "Mauritius", continent: "africa", path: "flags-svg/africa/MU.svg" },
  "MX": { name: "Mexico", continent: "north-america", path: "flags-svg/north-america/MX.svg" },
  "MD": { name: "Moldova", continent: "europe", path: "flags-svg/europe/MD.svg" },
  "MA": { name: "Morocco", continent: "africa", path: "flags-svg/africa/MA.svg" },
  "NL": { name: "Netherlands", continent: "europe", path: "flags-svg/europe/NL.svg" },
  "NG": { name: "Nigeria", continent: "africa", path: "flags-svg/africa/NG.svg" },
  "NO": { name: "Norway", continent: "europe", path: "flags-svg/europe/NO.svg" },
  "OM": { name: "Oman", continent: "asia", path: "flags-svg/asia/OM.svg" },
  "PS": { name: "Palestine", continent: "asia", path: "flags-svg/asia/PS.svg" },
  "PA": { name: "Panama", continent: "north-america", path: "flags-svg/north-america/PA.svg" },
  "PE": { name: "Peru", continent: "south-america", path: "flags-svg/south-america/PE.svg" },
  "PH": { name: "Philippines", continent: "asia", path: "flags-svg/asia/PH.svg" },
  "PL": { name: "Poland", continent: "europe", path: "flags-svg/europe/PL.svg" },
  "PT": { name: "Portugal", continent: "europe", path: "flags-svg/europe/PT.svg" },
  "PR": { name: "Puerto Rico", continent: "north-america", path: "flags-svg/north-america/PR.svg" },
  "QA": { name: "Qatar", continent: "asia", path: "flags-svg/asia/QA.svg" },
  "RU": { name: "Russia", continent: "europe", path: "flags-svg/europe/RU.svg" },
  "SA": { name: "Saudi Arabia", continent: "asia", path: "flags-svg/asia/SA.svg" },
  "RS": { name: "Serbia", continent: "europe", path: "flags-svg/europe/RS.svg" },
  "SG": { name: "Singapore", continent: "asia", path: "flags-svg/asia/SG.svg" },
  "SI": { name: "Slovenia", continent: "europe", path: "flags-svg/europe/SI.svg" },
  "ZA": { name: "South Africa", continent: "africa", path: "flags-svg/africa/ZA.svg" },
  "KR": { name: "South Korea", continent: "asia", path: "flags-svg/asia/KR.svg" },
  "ES": { name: "Spain", continent: "europe", path: "flags-svg/europe/ES.svg" },
  "SD": { name: "Sudan", continent: "africa", path: "flags-svg/africa/SD.svg" },
  "SE": { name: "Sweden", continent: "europe", path: "flags-svg/europe/SE.svg" },
  "CH": { name: "Switzerland", continent: "europe", path: "flags-svg/europe/CH.svg" },
  "SY": { name: "Syria", continent: "asia", path: "flags-svg/asia/SY.svg" },
  "TW": { name: "Taiwan", continent: "asia", path: "flags-svg/asia/TW.svg" },
  "TN": { name: "Tunisia", continent: "africa", path: "flags-svg/africa/TN.svg" },
  "TM": { name: "Turkmenistan", continent: "asia", path: "flags-svg/asia/TM.svg" },
  "TR": { name: "Türkiye", continent: "asia", path: "flags-svg/asia/TR.svg" },
  "AE": { name: "United Arab Emirates", continent: "asia", path: "flags-svg/asia/AE.svg" },
  "GB": { name: "United Kingdom", continent: "europe", path: "flags-svg/europe/GB.svg" },
  "US": { name: "United States", continent: "north-america", path: "flags-svg/north-america/US.svg" },
  "UY": { name: "Uruguay", continent: "south-america", path: "flags-svg/south-america/UY.svg" },
  "YE": { name: "Yemen", continent: "asia", path: "flags-svg/asia/YE.svg" },
};
